### ISSUE TITLE
Misspelling in the value for the query parameter 'type'

### ISSUE THREAD

**Issue by Mustycodes** [vdespa/introduction-to-postman-course#2]
On hitting the /books endpoint, the values for the query parameter **'type'** are supposed to be **'fiction'** and **'non-fiction'**, but the error message says _**'non-function'**_. Kindly try to correct this or provide a link to the api repo

**Comment by vdespa** [comment]
Thanks for reporting this. I have fixed the wrong error message.

The source code can be visible from here:

https://glitch.com/edit/#!/simple-books-api
